os: osx
osx_image: xcode12u

language: java


env:
  global:
    - PHARMGKB=$TRAVIS_BUILD_DIR/PharmGKB
    - PHARMGKB_USER=travis
    - ANT_VERSION=1.10.8
    - ANT_HOME=$TRAVIS_BUILD_DIR/apache-ant-${ANT_VERSION}
    - CATALINA_HOME=$TRAVIS_BUILD_DIR/tomcat
    # must change prompt; default prompt causes failure in ant
    - PS1="> "


jobs:
  - stage: Build
    before_install:
      - echo 'github.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==' >> ~/.ssh/known_hosts
      # install tomcat
      - echo "-------- install tomcat"
      - tc_url=`curl -s http://tomcat.apache.org/download-90.cgi | grep -oE 'href="https?:.*apache-tomcat-9.[0-9]+.[0-9]+.tar.gz"' | grep -o 'http.*.gz' | head -n1`
      - wget -q $tc_url
      - tc_gz=`basename $tc_url`
      - tar -xf $tc_gz
      - tc_dir=`basename $tc_url ".tar.gz"`
      - ln -s $tc_dir tomcat
      # install ant
      - echo "-------- install other dependencies"
      - wget https://www.apache.org/dist/ant/binaries/apache-ant-${ANT_VERSION}-bin.tar.gz
      - tar -xzvf apache-ant-${ANT_VERSION}-bin.tar.gz

    install:
      - git clone git@github.com:PharmGKB/PharmGKB.git PharmGKB
      - cd PharmGKB
      - git clone git@github.com:PharmGKB/pgkb-common.git pgkb-common
      - git clone git@github.com:PharmGKB/pgkb-common-io.git pgkb-common-io
      - cp passwords.properties.template passwords.properties

    script:
      - ant pathvisio-mac

