os: osx
osx_image: xcode9.3

language: java
go:
  - 1.x

env:
  global:
    - PHARMGKB=${TRAVIS_BUILD_DIR}/PharmGKB
    - PHARMGKB_USER=travis
    - ANT_HOME=$TRAVIS_BUILD_DIR/ant
    - CATALINA_HOME=${TRAVIS_BUILD_DIR}/tomcat
    - GOPATH=${TRAVIS_BUILD_DIR}/go
    # must change prompt; default prompt causes failure in ant
    - PS1="> "


before_install:
  - echo -e "machine github.com\n  login $GH_TOKEN" > ~/.netrc

install:
  # install tomcat
  - echo "-------- install tomcat"
  - tc_url=`curl -s http://tomcat.apache.org/download-90.cgi | grep -oE 'href="https?:.*apache-tomcat-9.[0-9]+.[0-9]+.tar.gz"' | grep -o 'http.*.gz' | head -n1`
  - wget -q $tc_url
  - tc_gz=`basename $tc_url`
  - tar -xf $tc_gz
  - tc_dir=`basename $tc_url ".tar.gz"`
  - ln -s $tc_dir tomcat
  # install ant
  - echo "-------- install ant"
  - ant_file=`curl -s https://downloads.apache.org/ant/binaries/ | grep -oE 'href="apache-ant-1.1[0-9].[0-9]+-bin.tar.gz"' | sed 's/"//g' | cut -c6-`
  - echo "Getting ${ant_file}"
  - wget https://www.apache.org/dist/ant/binaries/${ant_file}
  - tar -xzvf ${ant_file}
  - ant_dir=`basename $ant_file "-bin.tar.gz"`
  - ln -s $ant_dir ant
  # install github-release
  - echo "-------- install github-release"
  - go get github.com/github-release/github-release
  - export PATH=${GOPATH}/bin:${PATH}

before_script:
  - git clone https://github.com/PharmGKB/PharmGKB.git PharmGKB
  - cd PharmGKB
  - git clone https://github.com/PharmGKB/pgkb-common.git pgkb-common
  - git clone https://github.com/PharmGKB/pgkb-common-io.git pgkb-common-io
  - cp passwords.properties.template passwords.properties
  - export JAVA_HOME=$(/usr/libexec/java_home)

script:
  - ant pathvisio-mac

deploy:
  provider: script
  skip_cleanup: true
  script: ${PHARMGKB}/bin/uploadAssets-pathvisio.sh
  on:
    branch: main
