os: osx
osx_image: xcode9.3

language: java


env:
  global:
    - PHARMGKB=${TRAVIS_BUILD_DIR}/PharmGKB
    - PHARMGKB_USER=travis
    - ANT_VERSION=1.10.8
    - ANT_HOME=${TRAVIS_BUILD_DIR}/apache-ant-${ANT_VERSION}
    - CATALINA_HOME=${TRAVIS_BUILD_DIR}/tomcat
    - GOPATH=${TRAVIS_BUILD_DIR}/go
    # must change prompt; default prompt causes failure in ant
    - PS1="> "


before_install:
  - echo -e "machine github.com\n  login $GH_TOKEN" > ~/.netrc

install:
  # install tomcat
  - echo "-------- install tomcat"
  - tc_url=`curl -s http://tomcat.apache.org/download-90.cgi | grep -oE 'href="https?:.*apache-tomcat-9.[0-9]+.[0-9]+.tar.gz"' | grep -o 'http.*.gz' | head -n1`
  - wget -q $tc_url
  - tc_gz=`basename $tc_url`
  - tar -xf $tc_gz
  - tc_dir=`basename $tc_url ".tar.gz"`
  - ln -s $tc_dir tomcat
  # install ant
  - echo "-------- install ant"
  - wget https://www.apache.org/dist/ant/binaries/apache-ant-${ANT_VERSION}-bin.tar.gz
  - tar -xzvf apache-ant-${ANT_VERSION}-bin.tar.gz
  - export PATH=${ANT_HOME}/bin:${PATH}
  # install go (using https://github.com/travis-ci/gimme)
  - echo "-------- install go"
  - which brew
  - brew install gimme
  - gimme stable
  # install github-release
  - echo "-------- install github-release"
  - go get github.com/github-release/github-release
  - export PATH=${GOPATH}/bin:${PATH}

before_script:
  - git clone https://github.com/PharmGKB/PharmGKB.git PharmGKB
  - cd PharmGKB
  - git clone https://github.com/PharmGKB/pgkb-common.git pgkb-common
  - git clone https://github.com/PharmGKB/pgkb-common-io.git pgkb-common-io
  - cp passwords.properties.template passwords.properties
  - export JAVA_HOME=$(/usr/libexec/java_home)

script:
  - ant pathvisio-mac

deploy:
  provider: script
  skip_cleanup: true
  script: ${PHARMGKB}/bin/uploadAssets-pathvisio.sh
  on:
    branch: main
